### PR TITLE
BLD: Enable osx_arm64

### PR DESCRIPTION
**Pull request by hhslepicka**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hhslepicka** [comment]
@conda-forge-admin, please rerender

**Review by mrakitin — COMMENTED** [review]
I am fine with the changes, but not sure what's the rerendering problem. Can you reproduce it locally? Maybe it's an incomplete zip keys issue?

**Comment by hhslepicka** [comment]
@mrakitin yes! I was able to reproduce locally and I contacted conda-forge folks...
Until I rerender this should not be merged.

**Comment by mrakitin** [comment]
I see, I won't touch it then. Maybe convert it to "draft"?

**Comment by hhslepicka** [comment]
@mrakitin there were some issues related to the `conda_build_config.yaml`. More details here: https://gitter.im/conda-forge/conda-forge.github.io?at=605523c4563232374c2f9fef

Now this PR will cover osx_arm64 and Python 3.9

**Comment by hhslepicka** [comment]
@conda-forge-admin, please rerender

**Comment by hhslepicka** [comment]
@mrakitin SRW now working with osx-arm64... 
If you agree feel free to hit the big green button for us...

**Review by mrakitin — APPROVED** [review]
Looks good to me, thanks for the hard work, @hhslepicka!

**Comment by hhslepicka** [comment]
Thanks for review and merge, @mrakitin

**Pull request merged**
