### PR TITLE
Added conda_build_config.yaml with Py39

### PR DESCRIPTION
**Pull request by mrakitin**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by mrakitin** [comment]
I did not bump the build number as we only need the Py39 artifact which did not exist before.

**Review by hhslepicka — APPROVED** [review]
Looks good! I thought that you were going to wait for conda-forge to move to 3.9 before adding here but if tests are passing I would say go for it.

**Comment by mrakitin** [comment]
Yeah, I wanted to wait first, but then thought to give it a try to see if it passes at all.

**Comment by mrakitin** [comment]
> Hi! This is the friendly automated conda-forge-linting service.
> 
> I just wanted to let you know that I linted all conda-recipes in your PR (`recipe`) and found it was in an excellent condition.
> 
> I do have some suggestions for making it better though...
> 
> For **recipe**:
> 
>     * License is not an SPDX identifier (or a custom LicenseRef) nor an SPDX license expression.
> 
> 
> Documentation on acceptable licenses can be found [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#spdx-identifiers-and-expressions).

@hhslepicka, I thought your PR https://github.com/conda-forge/conda-smithy/pull/1456 should have fixed it.

**Comment by mrakitin** [comment]
Thanks for merging, by the way!

**Comment by hhslepicka** [comment]
It was merged but they need a new release for it to be used... I am not sure.

**Comment by mrakitin** [comment]
Oh, yes, I see. It may not be in production yet.

**Pull request merged**
