### PR TITLE
SRW 4.1.0 OSX fixes

### PR DESCRIPTION
**Pull request by himanshugoel2797**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Testing fix for OSX errors.

### CODE REVIEW

**Comment by mrakitin** [comment]
@conda-forge-admin, please rerender.

**Comment by mrakitin** [comment]
@himanshugoel2797, can you please check the "Allow edits from maintainers" box, so that I can push to your PR branch?

**Comment by himanshugoel2797** [comment]
Strange, allow edits by maintainers is already checked

**Comment by mrakitin** [comment]
I guess it's because you have a fork of a `regro-cf-autotick-bot` fork...

**Comment by himanshugoel2797** [comment]
Ah, probably. I'm out right now, but I'll try seeing if I can recreate my fork properly in the evening.

**Comment by mrakitin** [comment]
No worries! I actually incorporated building the new version in https://github.com/conda-forge/srwpy-feedstock/pull/17 and applied a [patch](https://github.com/conda-forge/srwpy-feedstock/pull/17/commits/33183f55e6000de374dab374e567f9b07e179622) to the SRW source code of v4.1.0 to fix the `no-implicit-int` error in the genesis code.

**Comment by mrakitin** [comment]
Closing as the new version was built via https://github.com/conda-forge/srwpy-feedstock/pull/17.

**Pull request closed without merging**
